### ISSUE TITLE
Deploy Alpaca to NPM

### ISSUE THREAD

**Issue by robustified** [gitana/alpaca#265]
On our project we are using Webpack to manage dependencies, and for the most part, opting for the NPM version of a dependency whenever possible means we reduce our need to manage separate npm and bower dependencies. We haven't found very many that aren't also available on NPM, but Alpaca is one of them. This would help us get one step closer to eliminating bower from our setup, and would provide flexibility to anyone else that would wish to do the same.

**Comment by hardeep** [comment]
+1 We're using browserify and this would be fantastic!

**Comment by uzquiano** [comment]
Good news - we can do this.  Thanks to the generosity of @alexanderjamesking, we're now able to use the "alpaca" name on NPM.  Therefore, we can add deployment to NPM using the same "alpaca" name as Bower.  

We'll make this part of the next release.  I just need to hook into the deployment script.

Many, many thanks to @alexanderjamesking on behalf of the community.  Now all of the Browserify and Webpack enthusiasts can be browserified and webpacked, respectively.

**Comment by uzquiano** [comment]
It's on NPM now.  The 1.5.9 release.

With 1.5.10 going out this week, we'll update NPM as part of the deploy process.  Should be all hooked up.

**Comment by acceptablehack** [comment]
Thanks very much for doing this! Is it possible to also include the build in the npm deploy? This prevents Webpack from including it the same way we can with the bower version.

**Comment by samrispaud** [comment]
@alexanderjamesking thank you! Doing an npm install and then running webpack does not seem to build the various src files in the 'build' folder of the alpaca node module. However cloning the repo and running npm start will do this. Do you have any insight into why this is not happening with npm and webpack? Thanks!

**Comment by uzquiano** [comment]
This should now be resolved, I think.  In the latest release, we package up the npm assets separately so that they get the build products.  There should be no need to do a separate build - everything is prebuilt now under dist.

**Comment by gabrielrobert** [comment]
@uzquiano Is there any docs that show how to include Alpaca in webpack projects? I can't find one and I am still unable to do it.

Thank you!

**Comment by ambischof** [comment]
@gabrielrobert you need to add the 'bower.json' to descriptionFiles https://webpack.js.org/configuration/resolve/#resolve-descriptionfiles
